
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;

public class cashierFrame extends javax.swing.JFrame {

    int nextBillNumber = 0;
    int cashierID = 0;
    int nextOrderID = 0;
    ArrayList<String> item = new ArrayList<>();
    ArrayList<Integer> itemQty = new ArrayList<>();
    int itemCounter = 0;
    boolean isDelivery = true;
    boolean isPickUp = false;

    public cashierFrame(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        Connecting2DB conn = new Connecting2DB();
        String q = "select name from item";
        conn.retriveToBox(itemsBox, q, "name");

        q = "select CAR_ID from Delivery_Car";
        conn.retriveToBox(carsBox, q, "CAR_ID");

        q = "select DRIVER_ID from driver";
        conn.retriveToBox(driversBox, q, "DRIVER_ID");

        q = "select max(bill#) from bill";
        String temp = conn.retriveOne(q, "max(bill#)");
        if (temp != null) {
            nextBillNumber = Integer.parseInt(temp) + 1;
        } else {
            nextBillNumber = 500;
        }
        q = "select max(order_id) from orders";
        temp = conn.retriveOne(q, "max(order_id)");
        if (temp != null) {
            nextOrderID = Integer.parseInt(temp) + 1;
        } else {
            nextOrderID = 400;
        }
        cashierID = id;
    }

    public cashierFrame(int cashierID, int customerID) {
        this(cashierID);
        customerIDFiled.setText(customerID + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        itemsBox = new javax.swing.JComboBox<>();
        qtyField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        confirmOrderType2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        changeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        paidFiled = new javax.swing.JTextField();
        totalField = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        paidBoutton = new javax.swing.JButton();
        printRecipt = new javax.swing.JButton();
        orderType = new javax.swing.JComboBox<>();
        driversBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        customerIDFiled = new javax.swing.JTextField();
        Calculate = new javax.swing.JButton();
        confirmOrderType1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        carsBox = new javax.swing.JComboBox<>();
        nameFiled = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(236, 240, 241))); // NOI18N

        qtyField.setEditable(false);
        qtyField.setBackground(new java.awt.Color(108, 122, 137));
        qtyField.setForeground(new java.awt.Color(228, 241, 254));
        qtyField.setText("0");

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        confirmOrderType2.setBackground(new java.awt.Color(27, 132, 190));
        confirmOrderType2.setForeground(new java.awt.Color(236, 240, 241));
        confirmOrderType2.setText("Confirm");
        confirmOrderType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmOrderType2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmOrderType2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))))
                .addGap(94, 94, 94))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(itemsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(confirmOrderType2))
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(236, 240, 241))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Total");

        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Paid");

        changeField.setBackground(new java.awt.Color(108, 122, 137));
        changeField.setForeground(new java.awt.Color(228, 241, 254));

        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("CHANGE");

        paidFiled.setEditable(false);
        paidFiled.setBackground(new java.awt.Color(108, 122, 137));
        paidFiled.setForeground(new java.awt.Color(228, 241, 254));
        paidFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidFiledActionPerformed(evt);
            }
        });

        totalField.setEditable(false);
        totalField.setBackground(new java.awt.Color(108, 122, 137));
        totalField.setForeground(new java.awt.Color(228, 241, 254));
        totalField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paidFiled, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalField)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3)))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paidFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(236, 240, 241))); // NOI18N

        paidBoutton.setText("Paid");
        paidBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidBouttonActionPerformed(evt);
            }
        });

        printRecipt.setBackground(new java.awt.Color(27, 132, 190));
        printRecipt.setForeground(new java.awt.Color(236, 240, 241));
        printRecipt.setText("Confirm Order");
        printRecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReciptActionPerformed(evt);
            }
        });

        orderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Pickup" }));
        orderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderTypeActionPerformed(evt);
            }
        });

        driversBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driversBoxActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Driver");

        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("CustomerID:");

        customerIDFiled.setBackground(new java.awt.Color(108, 122, 137));
        customerIDFiled.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customerIDFiled.setForeground(new java.awt.Color(228, 241, 254));
        customerIDFiled.setText("0");

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        confirmOrderType1.setBackground(new java.awt.Color(190, 26, 26));
        confirmOrderType1.setForeground(new java.awt.Color(236, 240, 241));
        confirmOrderType1.setText("New");
        confirmOrderType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmOrderType1ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Car");

        carsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsBoxActionPerformed(evt);
            }
        });

        nameFiled.setEditable(false);
        nameFiled.setBackground(new java.awt.Color(108, 122, 137));
        nameFiled.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameFiled.setForeground(new java.awt.Color(228, 241, 254));

        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("Name:");

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paidBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(printRecipt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(driversBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerIDFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(nameFiled))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmOrderType1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addComponent(Calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(orderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driversBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(customerIDFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(confirmOrderType1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Calculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paidBoutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printRecipt))
        );

        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBackground(new java.awt.Color(248, 148, 6));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("KAU Burgar ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("-");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printReciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReciptActionPerformed
        if (changeField.getText().isEmpty() || changeField.getText().equals(" ") || changeField.getText() == null) {
            JOptionPane.showMessageDialog(null, "You didn't pay yet!", null, JOptionPane.ERROR_MESSAGE);
        } else {
            double change = Double.parseDouble(changeField.getText());
            boolean orderIsConfirmed = false;
            if (change <= 0) {
                Connecting2DB conn = new Connecting2DB();
                String Type = (String) orderType.getSelectedItem();
                String q = "select sysdate from dual";
                String date = conn.retriveOne(q, "sysdate");
                int index = date.indexOf(" ");
                date = date.substring(0, index);
                double total = Double.parseDouble(totalField.getText());
                q = "insert into bill values( " + nextBillNumber + "," + total + ")";
                conn.insert_into_table(q);
                q = "insert into orders values( " + nextOrderID + " , '" + Type + "', to_date('" + date + "','yyyy/mm/dd'), " + cashierID + " ," + nextBillNumber + ")";
                conn.insert_into_table(q);
                if (isDelivery) {
                    try {
                        if (!customerIDFiled.getText().equals("")) {
                            int carID = Integer.parseInt((String) carsBox.getSelectedItem());
                            int driverID = Integer.parseInt((String) driversBox.getSelectedItem());
                            int customerID = Integer.parseInt((String) customerIDFiled.getText());
                            if (customerID > 0) {
                                String name = nameFiled.getText();
                                if (name == null) {
                                    JOptionPane.showMessageDialog(null, "Customer not Found!");
                                } else {
                                    q = "insert into delivery_order values (" + nextOrderID + "," + carID + "," + customerID + "," + driverID + ")";
                                    conn.insert_into_table(q);
                                    orderIsConfirmed = true;
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Customer ID in delivery order cannot be 0");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please Enter CUSTOMER ID!");
                        }
                    } catch (NumberFormatException NumberFormatException) {
                        JOptionPane.showMessageDialog(null, "Enter Numbers Only");
                    }

                } else {
                    int customerID = Integer.parseInt((String) customerIDFiled.getText());
                    q = "select name from customer where customer_id = " + customerID;
                    String name = conn.retriveOne(q, "name");
                    if (name == null) {
                        q = "insert into customer values(0,'default',null,null)";
                        conn.insert_into_table(q);
                    }
                    q = "insert into pickup_order values(" + nextOrderID + ", " + customerID + ")";
                    conn.insert_into_table(q);
                    orderIsConfirmed = true;
                }
                if (orderIsConfirmed) {
                    nextBillNumber++;
                    nextOrderID++;
                    new cashierFrame(cashierID).setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "change Must be <= 0", null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_printReciptActionPerformed

    private void paidBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidBouttonActionPerformed
        if (totalField.getText().isEmpty() || totalField.getText().equals(" ") || totalField.getText() == null) {
            JOptionPane.showMessageDialog(null, "Total Must be > 0", null, JOptionPane.ERROR_MESSAGE);
        } else {
            double paid = 0;
            try {
                paid = Double.parseDouble(JOptionPane.showInputDialog("How much?"));
                paidFiled.setText(paid + "");
                double total = Double.parseDouble(totalField.getText());
                double change = total - paid;
                changeField.setText(Double.toString(change));
            } catch (NumberFormatException NumberFormatException) {
                JOptionPane.showMessageDialog(null, "Enter Numbers Only");
            }
        }
    }//GEN-LAST:event_paidBouttonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new loginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void paidFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidFiledActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void orderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderTypeActionPerformed
        if (orderType.getSelectedItem().equals("Pickup")) {
            customerIDFiled.setEditable(false);
            customerIDFiled.setText("0");
            carsBox.setEnabled(false);
            driversBox.setEnabled(false);
            isPickUp = true;
            isDelivery = false;
            Connecting2DB conn = new Connecting2DB();
            int customerID = Integer.parseInt((String) customerIDFiled.getText());
            String q = "select name from customer where customer_id = " + customerID;
            String name = conn.retriveOne(q, "name");
            if (name == null) {
                q = "insert into customer values(0,'default',null,null)";
                conn.insert_into_table(q);
            }
        } else {
            customerIDFiled.setEditable(true);
            carsBox.setEnabled(true);
            driversBox.setEnabled(true);
            isPickUp = false;
            isDelivery = true;
        }
    }//GEN-LAST:event_orderTypeActionPerformed

    private void driversBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driversBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driversBoxActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        double total = 0.0;
        Connecting2DB conn = new Connecting2DB();
        if (item.size() > 0) {
            for (int i = 0; i < item.size(); i++) {
                String q = "select Price from item where name = '" + item.get(i) + "'";
                double price = Double.parseDouble(conn.retriveOne(q, "Price"));
                total += price * itemQty.get(i);
            }
            totalField.setText(total + "");
        } else {
            JOptionPane.showMessageDialog(null, "You didn't ADD any ITEM!");
        }
    }//GEN-LAST:event_CalculateActionPerformed

    private void confirmOrderType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmOrderType1ActionPerformed
        new customerFrame(cashierID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_confirmOrderType1ActionPerformed

    private void confirmOrderType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmOrderType2ActionPerformed
        int qty = Integer.parseInt(qtyField.getText());
        if (qty > 0) {
            String currentItem = (String) itemsBox.getSelectedItem();
            item.add(itemCounter, currentItem);
            itemQty.add(itemCounter, qty);
        }
        qtyField.setText("0");
    }//GEN-LAST:event_confirmOrderType2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int qty = Integer.parseInt(qtyField.getText());
        qty++;
        qtyField.setText(qty + "");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int qty = Integer.parseInt(qtyField.getText());
        if (qty > 0) {
            qty--;
            qtyField.setText(qty + "");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carsBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Connecting2DB conn = new Connecting2DB();
            int customerID = Integer.parseInt((String) customerIDFiled.getText());
            String q = "select name from customer where customer_id = " + customerID;
            String name = conn.retriveOne(q, "name");
            if (name == null) {
                JOptionPane.showMessageDialog(null, "Customer not Found!");
            } else {
                nameFiled.setText(name);
            }
        } catch (NumberFormatException NumberFormatException) {
            JOptionPane.showMessageDialog(null, "Enter Numbers Only");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginFrame.Run();
            }
        });
    }

    public static boolean answer(int i) {
        if (i == 0) {
            return true;
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculate;
    private javax.swing.JComboBox<String> carsBox;
    private javax.swing.JTextField changeField;
    private javax.swing.JButton confirmOrderType1;
    private javax.swing.JButton confirmOrderType2;
    private javax.swing.JTextField customerIDFiled;
    private javax.swing.JComboBox<String> driversBox;
    private javax.swing.JComboBox<String> itemsBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField nameFiled;
    private javax.swing.JComboBox<String> orderType;
    private javax.swing.JButton paidBoutton;
    private javax.swing.JTextField paidFiled;
    private javax.swing.JButton printRecipt;
    private javax.swing.JTextField qtyField;
    private javax.swing.JFormattedTextField totalField;
    // End of variables declaration//GEN-END:variables
}
